### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by mark9064** [volca02/spoof_vendorid#1]
Hey I know this is just a test really, but any chance you could help me out trying to get this to build? So far I've installed the dependencies listed in the linux vulkansdk, and done:
```
mkdir build
cmake ..
make
```
which results in
```
[ 18%] Linking CXX shared library libVkLayer_cmake.so
/usr/bin/ld: cannot find -lVkLayer_utils
collect2: error: ld returned 1 exit status
CMakeFiles/VkLayer_cmake.dir/build.make:94: recipe for target 'libVkLayer_cmake.so' failed
make[2]: *** [libVkLayer_cmake.so] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/VkLayer_cmake.dir/all' failed
make[1]: *** [CMakeFiles/VkLayer_cmake.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by volca02** [comment]
The file `libVkLayer_utils.a` is in `x86_64/lib` - maybe I didn't rewrite all the link paths correctly.

**Comment by mark9064** [comment]
Any dirty fix to get it going for now? (copy it somewhere else or something)

EDIT: just saw commit

**Comment by mark9064** [comment]
OK it built :smile:

**Comment by volca02** [comment]
great. hope it fixes the game for you as well.
